CREATE TABLE IF NOT EXISTS User (
    usr_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(72) NOT NULL, -- bcryptの最大長が72らしい
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Tweet (
    tw_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usr_id INT NOT NULL,
    body VARCHAR(280) NOT NULL,
    replied_to BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_usr_id(usr_id, created_at DESC),
    INDEX idx_replied_to(replied_to, created_at DESC),
    FOREIGN KEY (usr_id) REFERENCES User(usr_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Favorite (
    tw_id BIGINT UNSIGNED NOT NULL,
    usr_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tw_id, usr_id),
    FOREIGN KEY (tw_id) REFERENCES Tweet(tw_id) ON DELETE CASCADE,
    FOREIGN KEY (usr_id) REFERENCES User(usr_id) ON DELETE CASCADE
);
