name: Docker Image CI

on:
  push: ~
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/yumetter-api

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yumetter-api
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: a-omori-yumemi
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: $IMAGE_ID:${GITHUB_REF////-}-latest
