name: Docker Image CI

on:
  push: ~
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yumetter-api
    - name: Login ghcr
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u a-omori-yumemi --password-stdin
    - name: Push image
      run: |
        GITHUB_REF=${{ github.ref }} IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${GITHUB_REF#refs/heads}
        echo $IMAGE_ID
        docker tag yumetter-api $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
